package symbols

// Aliases maps a ticker to curated alternate search terms — chiefly the
// company's common Chinese name — so zh-first users can search "英伟达" and get
// NVDA. Merged into the search index by Build; CJK aliases are matched by the
// alias path in Search, ASCII aliases also feed the keyword token index.
//
// Hand-curated for the most-searched US names + a few ADRs/index ETFs. Not
// exhaustive (the SEC directory already covers English names/tickers); this is
// the "search by Chinese name" layer. Extend as needed.
func Aliases() map[string][]string {
	return map[string][]string{
		// Mega-cap tech
		"AAPL":  {"苹果"},
		"MSFT":  {"微软"},
		"NVDA":  {"英伟达", "辉达"},
		"GOOGL": {"谷歌", "Alphabet"},
		"GOOG":  {"谷歌", "Alphabet"},
		"AMZN":  {"亚马逊"},
		"META":  {"脸书", "Meta"},
		"TSLA":  {"特斯拉"},
		"AVGO":  {"博通"},
		"ORCL":  {"甲骨文"},
		"CRM":   {"赛富时", "Salesforce"},
		"ADBE":  {"奥多比", "Adobe"},
		"AMD":   {"超威", "超微"},
		"INTC":  {"英特尔"},
		"MU":    {"美光"},
		"ARM":   {"安谋", "Arm"},
		"QCOM":  {"高通"},
		"TXN":   {"德州仪器"},
		"IBM":   {"国际商业机器"},
		"CSCO":  {"思科"},
		"NFLX":  {"奈飞", "网飞"},
		"DIS":   {"迪士尼"},
		"UBER":  {"优步"},
		"ABNB":  {"爱彼迎"},
		"SHOP":  {"Shopify"},
		"PYPL":  {"PayPal"},
		"PLTR":  {"Palantir"},
		"HOOD":  {"罗宾汉", "Robinhood"},
		"COIN":  {"Coinbase"},
		"SNOW":  {"雪花", "Snowflake"},
		"SMCI":  {"美超微"},
		"DELL":  {"戴尔"},
		"HPQ":   {"惠普"},
		"SONY":  {"索尼"},
		// Chinese ADRs (heavily searched by zh users)
		"BABA": {"阿里巴巴", "阿里"},
		"PDD":  {"拼多多"},
		"JD":   {"京东"},
		"BIDU": {"百度"},
		"NTES": {"网易"},
		"TCOM": {"携程"},
		"NIO":  {"蔚来"},
		"LI":   {"理想汽车", "理想"},
		"XPEV": {"小鹏汽车", "小鹏"},
		"BILI": {"哔哩哔哩", "B站"},
		"TME":  {"腾讯音乐"},
		"BEKE": {"贝壳"},
		"ZTO":  {"中通"},
		"YUMC": {"百胜中国"},
		"LU":   {"陆金所"},
		"FUTU": {"富途"},
		"TIGR": {"老虎证券"},
		// Finance
		"JPM":   {"摩根大通", "小摩"},
		"GS":    {"高盛"},
		"MS":    {"摩根士丹利", "大摩"},
		"BAC":   {"美国银行", "美银"},
		"WFC":   {"富国银行"},
		"C":     {"花旗"},
		"V":     {"维萨", "Visa"},
		"MA":    {"万事达"},
		"AXP":   {"美国运通", "运通"},
		"BRK.B": {"伯克希尔", "巴菲特"},
		"BRK.A": {"伯克希尔", "巴菲特"},
		"BLK":   {"贝莱德"},
		// Consumer / industrial / health / energy
		"KO":   {"可口可乐"},
		"PEP":  {"百事"},
		"WMT":  {"沃尔玛"},
		"COST": {"好市多", "开市客"},
		"MCD":  {"麦当劳"},
		"SBUX": {"星巴克"},
		"NKE":  {"耐克"},
		"PG":   {"宝洁"},
		"PFE":  {"辉瑞"},
		"MRNA": {"莫德纳", "Moderna"},
		"JNJ":  {"强生"},
		"LLY":  {"礼来"},
		"UNH":  {"联合健康"},
		"XOM":  {"埃克森美孚", "埃克森"},
		"CVX":  {"雪佛龙"},
		"BA":   {"波音"},
		"CAT":  {"卡特彼勒"},
		"GE":   {"通用电气"},
		"F":    {"福特"},
		"GM":   {"通用汽车"},
		"LMT":  {"洛克希德马丁"},
		"MMM":  {"3M"},
		// ADRs / foreign majors often searched in Chinese
		"TSM":  {"台积电"},
		"ASML": {"阿斯麦"},
		"TM":   {"丰田"},
		"SAP":  {"思爱普"},
		"NVO":  {"诺和诺德"},
		"SHEL": {"壳牌"},
		"HSBC": {"汇丰"},
		// Index ETFs
		"SPY": {"标普500", "标普"},
		"VOO": {"标普500"},
		"QQQ": {"纳指100", "纳斯达克100"},
		"DIA": {"道琼斯"},
		"IWM": {"罗素2000"},
	}
}
