/**
 * UI-chrome translation strings (English / 简体中文). Extracted from i18n.tsx as
 * plain data (NO React, NOT 'use client') so Server Components, generateMetadata
 * and the server translator {@link getT} can import it. Keep keys dotted-
 * namespaced; add new keys to BOTH maps — missing zh keys fall back to en.
 */

import type {Lang} from '@/lib/i18n';

export const dict: Record<Lang, Record<string, string>> = {
  en: {
    // top nav
    'nav.markets': 'Markets',
    'nav.hot': 'Hot',
    'nav.news': 'News',
    'nav.opportunities': 'Opportunities',
    'nav.events': 'Events',
    'nav.congress': 'Congress',
    'nav.institutional': 'Institutions',
    'nav.smartMoney': 'Smart money',
    'nav.screen': 'Screener',
    'nav.stocks': 'All stocks',
    'nav.watchlist': 'Watchlist',
    'nav.notes': 'Notes',
    'nav.community': 'Community',
    'nav.ipo': 'IPO calendar',
    'nav.calendar': 'Calendar',
    'nav.discussion': 'Discussion',
    'nav.my': 'My',
    'nav.more': 'More',
    'nav.whatsnew': "What's new",
    'nav.login': 'Log in',
    'nav.signup': 'Sign up',
    'nav.search': 'Search a stock…',
    'nav.myWatchlist': 'My watchlist',
    'nav.settings': 'Settings',
    'nav.signout': 'Sign out',
    'nav.account': 'Account menu',
    'nav.signedIn': 'Signed in',
    'nav.menu': 'Menu',
    // trading-session badge
    'session.pre': 'Pre-market',
    'session.regular': 'Regular',
    'session.post': 'After-hours',
    'session.overnight': 'Overnight',
    'session.closed': 'Closed',
    // fundamentals card
    'fund.title': 'Fundamentals',
    'fund.marketCap': 'Market cap',
    'fund.pe': 'P/E',
    'fund.revenue': 'Revenue',
    'fund.netIncome': 'Net income',
    'fund.eps': 'EPS',
    'fund.pb': 'P/B',
    'fund.loss': 'Loss',
    'fund.source': 'Source: SEC filings',
    // per-stock indicators panel
    'ind2.title': 'Indicators',
    'ind2.asOf': 'as of {d}',
    'ind2.domain.technical': 'Technical',
    'ind2.domain.fundamental': 'Fundamental',
    'ind2.domain.sentiment': 'Sentiment',
    'ind2.vix': 'VIX',
    'ind2.fearGreed': 'Fear & Greed',
    'ind2.learnMore': 'View in the indicator library',
    'ind2.empty': '—',
    // anonymous preview gate (sign in to see the full indicator set)
    'ind2.gate.title': 'Sign in to see all {n} indicators',
    'ind2.gate.sub': "You're viewing a preview. Sign in to unlock the full set and customize it.",
    'ind2.gate.cta': 'Sign in to view all',
    // indicator picker (customize the selected indicators)
    'ind2.picker.customize': 'Customize',
    'ind2.picker.title': 'Customize indicators',
    'ind2.picker.selected': 'Selected',
    'ind2.picker.search': 'Search indicators…',
    'ind2.picker.allDomains': 'All',
    'ind2.picker.add': 'Add',
    'ind2.picker.remove': 'Remove',
    'ind2.picker.reset': 'Reset to default',
    'ind2.picker.count': '{n} selected',
    'ind2.picker.empty': 'No indicators selected — add some below.',
    'ind2.picker.noMatch': 'No indicators match your search.',
    'ind2.picker.moveUp': 'Move up',
    'ind2.picker.moveDown': 'Move down',
    'ind2.picker.close': 'Close',
    // signals (deterministic posture signals derived from the computed indicators)
    'signals.title': 'Signals',
    'signals.asOf': 'as of {d}',
    'signals.empty': 'No active signals right now.',
    'signals.dir.bullish': 'Bullish',
    'signals.dir.bearish': 'Bearish',
    'signals.dir.neutral': 'Neutral',
    'signals.trust': 'Each signal is a deterministic rule over a computed indicator — never advice or a price target.',
    'signals.locked.title': 'More signals with Pro',
    'signals.locked.body':
      'Pro opens the full signal set — every one a transparent rule over a computed number, never advice.',
    'signals.locked.cta': 'Unlock {n} more',
    // earnings
    'quote.lastTrade': 'Last trade {t} ago · {src}',
    'quote.lastTradeNow': 'Last trade just now · {src}',
    'options.title': 'Options',
    'options.delayed': 'Delayed 15 min · Cboe',
    'options.pcVol': 'Put/Call (Vol)',
    'options.pcOI': 'Put/Call (OI)',
    'options.maxPain': 'Max Pain',
    'options.topOI': 'Top open interest',
    'options.kind': 'Type',
    'options.call': 'CALL',
    'options.put': 'PUT',
    'options.strike': 'Strike',
    'options.expiry': 'Expiry',
    'options.oi': 'OI',
    'options.vol': 'Vol',
    'options.iv': 'IV',
    // unusual options board
    'nav.unusual': 'Unusual options',
    'unusual.title': 'Unusual options activity',
    'unusual.subtitle': 'Contracts trading the most volume today across heavily-optioned US names — a read on where the options crowd is piling in.',
    'unusual.empty': 'No unusual activity yet — the board is still scanning the market.',
    'unusual.ticker': 'Ticker',
    'unusual.volOI': 'Vol/OI',
    // 13F whale holdings
    '13f.tab': 'Whale 13F',
    '13f.title': 'Whale holdings · 13F',
    '13f.subtitle': 'What famous fund managers held last quarter — Buffett, Burry, Ackman, Li Lu and more, from their SEC 13F filings.',
    '13f.disclaimer': '13F holdings are filed ~45 days after quarter-end — a historical snapshot of long positions only (no shorts or options), from public SEC data. Not investment advice.',
    '13f.asOf': 'as of',
    '13f.empty': 'No holdings yet',
    '13f.emptySub': 'Fetching the latest 13F filings — check back shortly.',
    '13f.footer': 'Source: SEC 13F-HR filings (public domain); CUSIP→ticker via OpenFIGI. Not investment advice.',
    '13f.colStock': 'Stock',
    '13f.colValue': 'Value',
    '13f.colPct': 'Weight',
    '13f.colChange': 'QoQ',
    '13f.change.new': 'New',
    '13f.change.add': 'Add',
    '13f.change.trim': 'Trim',
    '13f.change.hold': 'Hold',
    'whales.title': 'Institutional whales',
    'whales.weight': '{w}% of portfolio',
    'whales.more': '+{n} more',
    'brief.title': 'Morning Briefing',
    'brief.empty': "Today's briefing isn't generated yet — check back before the open.",
    'ai.title': 'AI Digest',
    'ai.badge': 'AI generated',
    'ai.loading': 'Reading the latest…',
    'ai.disclaimer': 'AI-generated from recent news & community posts · for reference only · not investment advice',
    // Move-explainer card: a move-triggered, evidence-grounded explanation of a
    // notable (|change| >= 5%) daily move. The % is Go-owned; the prose hedges.
    'move.title': "Why's it moving?",
    'move.aiBadge': 'AI generated',
    'move.evidence': 'Possibly related',
    'move.type.news': 'News',
    'move.type.filing': 'Filing',
    'move.type.insider': 'Insider buy',
    'move.disclaimer': 'AI generated · for reference only · not investment advice. The move % is computed from data; the explanation is a hedged guess, not a confirmed cause.',
    'move.disclaimerData': 'Move % computed from data · for reference only · not investment advice. No confirmed cause.',
    // 8-K material events + AI summary card
    'filings.title': 'Material events (8-K)',
    'filings.aiBadge': 'AI summary',
    'filings.amendment': 'Amendment',
    'filings.viewSource': 'View on SEC',
    'filings.reportDate': 'Event date',
    'filings.empty': 'No recent material events',
    'filings.source': 'Source: SEC EDGAR',
    'filings.asOf': 'as of',
    'filings.disclaimer': 'Filing facts (form, dates, item categories) are from SEC EDGAR. The summary is AI-generated for reference only, not investment advice.',
    // Insider-activity (Form 4 buy/sell) timeline card
    'insider.title': 'Insider activity (Form 4)',
    'insider.buy': 'BUY',
    'insider.sell': 'SELL',
    'insider.planned': '10b5-1 plan',
    'insider.plannedTitle': 'Sale under a pre-arranged Rule 10b5-1 trading plan — carries less signal than a discretionary sale.',
    'insider.shares': 'shares',
    'insider.atPrice': '@',
    'insider.viewSource': 'View on SEC',
    'insider.empty': 'No recent insider transactions',
    'insider.source': 'Source: SEC EDGAR Form 4',
    'insider.asOf': 'as of',
    'insider.delay': 'Form 4 is filed within 2 business days of the trade.',
    'insider.net': 'Net',
    'insider.buys': 'buys',
    'insider.sells': 'sells',
    // R2 deep-research report (chrome English-default; the report body is zh-by-design)
    'research.tab': 'Research',
    'research.title': 'Deep research',
    'research.loading': 'Assembling the report…',
    'research.asOf': 'as of {d}',
    'research.label': 'AI-generated · figures from public data · not investment advice',
    'research.dataOnly': 'AI summary unavailable — showing data only.',
    'research.sources': 'Sources',
    'research.bull': 'Bull case',
    'research.bear': 'Bear case',
    'research.insufficient': 'Insufficient data',
    'research.empty': 'No data for this ticker yet.',
    // Deep Research (gated, login-required) report view + AI-Digest entry button
    'deep.entry': 'Deep Research',
    'deep.title': 'AI Deep Research',
    'deep.subtitle': 'A source-attributed, AI-written analyst report for {t}.',
    'deep.trust': 'Every figure is drawn from public filings — the AI writes the analysis, never the numbers.',
    'deep.back': 'Back to {t}',
    'deep.overview': 'Executive overview',
    'deep.generating': 'Generating deep research…',
    'deep.generatingSub': 'A stronger model is reading the public data — this can take 10–60s.',
    'deep.proseGenerating': 'Generating AI analysis…',
    'deep.proseSlow': 'Taking a while — retry',
    'deep.proseQuota': 'Monthly deep-research limit reached',
    'deep.facts': 'Key figures',
    'deep.factsCol': 'Metric',
    'deep.valueCol': 'Value',
    'deep.sourceCol': 'Source · as of',
    'deep.priceChart': 'Price (5-year)',
    'deep.exportPdf': 'Export PDF',
    'deep.gate.title': 'Log in to unlock AI Deep Research',
    'deep.gate.body': 'A deeper, source-attributed analyst report for {t} — multi-section valuation, fundamentals, technicals, smart-money and sentiment, every number drawn from public data. Free for logged-in members.',
    'deep.gate.cta': 'Log in to continue',
    'deep.gate.preview': 'Preview',
    'deep.gate.previewNote': 'A preview of the public research — log in for the full deep report.',
    'deep.quota.title': 'Monthly deep-research limit reached',
    'deep.quota.body': "You've used your deep-research generations for this month — they reset next month. Or open a stock whose report was already generated this month (free to view).",
    'deep.error.title': 'Could not load the deep report',
    'deep.error.retry': 'Try again',
    'deep.locked.section': 'Unlock this section with Tickwind Pro.',
    'deep.paywall.title': 'Unlock the full deep report',
    'deep.paywall.body': "You're viewing the free preview — the overview and one section. Tickwind Pro unlocks every section, the bull & bear verdict, on-demand refresh, and PDF export. Every figure stays sourced from public data — Pro just opens the full read.",
    'deep.paywall.cta': 'See Pro plans',
    'pro.title': 'Tickwind Pro',
    'pro.subtitle': 'Full AI Deep Research and more — every figure still sourced from public data.',
    'pro.annual': 'Annual',
    'pro.monthly': 'Monthly',
    'pro.save': 'save ~36%',
    'pro.mo': 'mo',
    'pro.billedAnnually': 'Billed $99 / year',
    'pro.billedMonthly': 'Billed monthly',
    'pro.feat1': 'Every section of the AI Deep Research report — valuation, fundamentals, technicals, smart-money flows, sentiment',
    'pro.feat2': 'The full bull & bear verdict on every stock',
    'pro.feat3': 'On-demand refresh for the latest data, anytime',
    'pro.feat4': 'Branded PDF & share-image export',
    'pro.trust': 'AI writes the analysis; it never invents a number — every figure is drawn from public filings and sourced.',
    'pro.cta': 'Subscribe',
    'pro.ctaLogin': 'Log in to subscribe',
    'pro.err': "Couldn't start checkout — please try again.",
    'pro.cancel': 'Cancel anytime.',
    'pro.disclaimer': 'Tickwind provides objective summaries of public data, not investment advice.',
    'pro.success.title': "You're Pro 🎉",
    'pro.success.body': 'Your subscription is active — the full deep report and Pro features are unlocked.',
    'pro.success.cta': 'Start exploring',
    'short.title': 'Short pressure',
    'short.dtc': 'Days to cover',
    'short.qty': 'Short interest',
    'short.risk': 'Squeeze risk',
    'short.asof': 'as of {d}',
    // daily short-volume facet (finrashvol)
    'short.todayPct': "Today's short",
    'short.dailyTrend': 'Short % trend',
    'short.dailyAsof': 'Daily · as of {d}',
    // market-wide today's-short-volume board (one /hot tab)
    'shortvol.tab': 'Short volume',
    'shortvol.title': "Today's short-volume leaders",
    'shortvol.blurb':
      'US stocks with the highest share of today’s reported volume sold short — a fast-cadence read on intraday short pressure.',
    'shortvol.colSymbol': 'Symbol',
    'shortvol.colShortPct': 'Short %',
    'shortvol.colVolume': 'Volume',
    'shortvol.empty': 'No short-volume data yet',
    'shortvol.emptySub': "The board fills in once today's FINRA short-volume data is in.",
    'shortvol.asof': 'as of {d}',
    'shortvol.footer': 'Source: FINRA short-sale volume. Not investment advice.',
    // fear & greed index (home hub chip)
    'sentiment.title': 'Fear & Greed',
    'sentiment.extremeFear': 'Extreme Fear',
    'sentiment.fear': 'Fear',
    'sentiment.neutral': 'Neutral',
    'sentiment.greed': 'Greed',
    'sentiment.extremeGreed': 'Extreme Greed',
    'sentiment.components': 'What goes into it',
    'sentiment.trend': 'Recent trend',
    'sentiment.trendDays': '{n} days',
    'sentiment.updated': 'updated {t} ago',
    'sentiment.footer': 'Tickwind composite index. Methodology — not investment advice.',
    // macro strip — U.S. Treasury yield curve (2s10s recession signal)
    'macro.title': 'Treasury yields',
    'macro.spread': '2s10s spread',
    'macro.inverted': 'Inverted',
    'macro.normal': 'Normal',
    'macro.invertedHint': 'Inverted curve (10Y < 2Y) — a classic recession-watch signal',
    'macro.normalHint': 'Upward-sloping curve (10Y > 2Y)',
    'macro.updated': 'as of {t}',
    'crypto.title': 'Crypto mood',
    'crypto.extremeFear': 'Extreme Fear',
    'crypto.fear': 'Fear',
    'crypto.neutral': 'Neutral',
    'crypto.greed': 'Greed',
    'crypto.extremeGreed': 'Extreme Greed',
    'crypto.updated': 'as of {t}',
    // share card ("propagation organ") — save/share a branded image card
    'share.save': 'Save image',
    'share.aria': 'Open a shareable image card in a new tab',
    'earnings.next': 'Next earnings',
    'earnings.estEps': 'Est. EPS',
    'earnings.bmo': 'Pre-market',
    'earnings.amc': 'After-hours',
    'earnings.dmh': 'During hours',
    'nav.earnings': 'Earnings',
    'news.aiTranslated': 'AI',
    'earnings.calTitle': 'Earnings calendar',
    'earnings.calSubtitle': 'Upcoming US company reports, grouped by day · est. vs actual EPS',
    'earnings.calEmpty': 'No upcoming earnings',
    'earnings.calEmptySub': 'Check back soon — the calendar refreshes through the day.',
    'earnings.est': 'Est.',
    'earnings.act': 'Act.',
    // alerts
    'alerts.title': 'Alerts',
    'alerts.kind': 'Condition',
    'alerts.priceAbove': 'Price above',
    'alerts.priceBelow': 'Price below',
    'alerts.pctMove': 'Daily move',
    'alerts.newFiling': 'New SEC filing',
    'alerts.threshold': 'Price',
    'alerts.percent': 'Percent',
    'alerts.add': 'Add alert',
    'alerts.hint': "We'll watch this stock and flag it when the condition is met.",
    'alerts.empty': 'No alerts for this stock yet.',
    'alerts.delete': 'Delete alert',
    'alerts.deliveryNote': 'Triggered alerts will appear in-app. (Push notifications coming soon.)',
    'alerts.triggered': 'Triggered',
    'nav.alerts': 'Alerts',
    'alerts.centerTitle': 'Alerts',
    'alerts.centerSubtitle': 'Your price & event alerts across every stock — triggered and active.',
    'alerts.centerEmpty': 'No alerts yet. Add one from any stock page.',
    'alerts.loginToView': 'Sign in to see your alerts.',
    'alerts.active': 'Active',
    'alerts.rearm': 'Re-arm',
    'alerts.rearmed': 'Alert re-armed',
    // home hub
    'home.title': 'Markets today',
    'home.subtitle':
      'Live prices, then the trends, news and chatter across the market — all in one place.',
    'home.indices': 'Major indices',
    'home.hotTopics': 'Hot Topics',
    'search.title': 'Search',
    'search.hint': 'Type a ticker or company name above to search.',
    'search.for': 'Results for "{q}"',
    'search.searching': 'Searching…',
    'search.empty': 'No symbols match "{q}".',
    'search.emptyHint':
      "It may be a pink-sheet / OTC ticker we don't index yet — you can still open it directly.",
    'search.gotoAnyway': 'Go to {q}',
    'topic.heating': 'Heating up',
    'topic.sub': 'Stocks and news tied to {t}',
    'topic.stocks': 'Related stocks',
    'topic.news': 'Related news',
    'topic.empty': 'Topic not found',
    'topic.emptySub': "This topic isn't trending right now.",
    'topic.noNews': 'No related news yet',
    'topic.noNewsSub': 'Check back as the story develops.',
    'holdings.title': 'Holdings',
    'holdings.shares': 'Shares',
    'holdings.avgCost': 'Avg cost',
    'holdings.value': 'Value',
    'holdings.pl': 'Gain / loss',
    'holdings.save': 'Save',
    'holdings.remove': 'Remove',
    'holdings.empty': 'No position yet — enter your shares and average cost above.',
    'holdings.hint': 'Saved privately. Current value and P/L update with the live price.',
    'nav.portfolio': 'Portfolio',
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'Your positions, valued live.',
    'portfolio.total': 'Total value',
    'portfolio.totalCost': 'Total cost',
    'portfolio.dayPL': "Today's P/L",
    'portfolio.totalPL': 'Total P/L',
    'portfolio.allocation': 'Portfolio weight',
    'portfolio.allocShort': 'wt',
    'portfolio.ticker': 'Ticker',
    'portfolio.price': 'Price',
    'portfolio.empty': 'No holdings yet',
    'portfolio.emptySub': 'Add a position from any stock page — the Holdings tab.',
    'portfolio.someUnpriced': 'Some holdings have no live price yet and are excluded from the total.',
    'portfolio.disclaimer': 'For tracking only — not investment advice. Totals are summed nominally across currencies.',
    'mod.hotStocks': 'Hot stocks',
    'mod.opportunity': 'Opportunity',
    'mod.guru': 'Guru-watch',
    'mod.news': 'News',
    'mod.discussion': 'Discussion',
    'mod.fullBoard': 'Full board',
    'mod.seeAll': 'See all',
    'mod.showMore': 'Show {n} more',
    'mod.showLess': 'Show less',
    'mkt.allStocks': 'All stocks',
    'mod.moreNews': 'More news',
    'mod.joinIn': 'Join in',
    'mod.noData': 'No data yet',
    'mod.noSignals': 'No signals yet',
    'mod.noPosts': 'No posts yet',
    'mod.noNews': 'No news yet',
    'mod.noChatter': 'No chatter yet',
    // opportunity board
    'opp.title': 'Opportunity board',
    'opp.subtitle':
      'Small-cap US stocks where company insiders are buying on the open market — surfaced from SEC Form 4 filings.',
    'opp.disclaimer':
      'Rows are surfaced by data signals (insider open-market buying), not recommendations. Inclusion is not a rating or a suggestion to buy. Small-caps can be volatile and illiquid. Not investment advice.',
    'opp.empty': 'No insider-buy signals yet',
    'opp.emptySub': 'The board fills in as recent SEC Form 4 open-market buys are filed.',
    'opp.smallCap': 'Small cap',
    'opp.viewFiling': 'View SEC filing',
    'opp.footer': 'Insider data from public SEC EDGAR filings. Not investment advice.',
    // congress
    'congress.title': 'Congress trading',
    'congress.subtitle': 'Latest U.S. House stock-trade disclosures (Periodic Transaction Reports).',
    'congress.disclaimer':
      'Official U.S. House financial disclosures (public-domain Clerk data). Reflects when a filing was made, not real-time trades. Not investment advice.',
    'congress.filed': 'Filed',
    'congress.viewFiling': 'View official filing',
    'congress.empty': 'No recent filings',
    'congress.emptySub': 'Periodic Transaction Reports will appear here as they are filed.',
    'congress.footer': 'Source: U.S. House Clerk financial disclosures (public domain). Not investment advice.',
    // congress member detail page (pSEO)
    'member.eyebrow': 'Congress trades',
    'member.tradesTitle': 'Disclosed trades',
    'member.colDate': 'Date',
    'member.colType': 'Type',
    'member.colAsset': 'Asset',
    'member.colAmount': 'Amount',
    'member.owner.self': 'Self',
    'member.owner.spouse': 'Spouse',
    'member.owner.joint': 'Joint',
    'member.owner.child': 'Child',
    'member.type.purchase': 'Buy',
    'member.type.sale': 'Sell',
    'member.type.exchange': 'Exchange',
    'member.empty': 'No disclosed trades',
    'member.emptySub': 'No Periodic Transaction Reports are on file for this member yet.',
    'member.disclaimer':
      'Public data (U.S. House Clerk). Disclosures lag up to 45 days and show only amount ranges — not real-time trades, and not investment advice.',
    'member.footer': 'Source: U.S. House Clerk financial disclosures (public domain). Not investment advice.',
    // follow-trade simulation (historical replay) on the member page
    'sim.title': 'Follow-trade simulation',
    'sim.subtitle':
      'A historical replay: virtually buying each disclosed purchase at its disclosure-date close, held to today, vs. buying SPY on the same days.',
    'sim.vs': 'vs SPY',
    'sim.statSuffix': 'simulated follow vs SPY',
    'sim.member': 'Follow',
    'sim.spy': 'SPY',
    'sim.method': 'Method',
    'sim.methodBody':
      'Each disclosed BUY enters equal-weight at the disclosure-date close (the price a follower could actually have paid — disclosures lag up to ~45 days). A position is held to today, or closed at the disclosure-date close of a later SELL. Benchmark = the same equal dollar into SPY on each buy date, held to today. Daily closes only, gross of fees/taxes.',
    'sim.notReal':
      'Simulated historical replay — NOT realized returns, NOT investment advice. Equal-weighted, based on public disclosures that lag real trades.',
    'sim.coverage': 'Coverage',
    'sim.coverageBody': '{used} trades simulated · {skipped} skipped (no price history)',
    'sim.windowNote': 'Window: {start} → today ({months} mo)',
    'sim.insufficient': 'Not enough data to simulate',
    'sim.insufficientSub':
      'This member has no disclosed purchases with usable price history yet, so a follow-trade replay can’t be computed.',
    // congress chip on the stock detail page (members' recent trades in a ticker)
    'cchip.title': 'Congress trades',
    'cchip.buy': 'Buy',
    'cchip.sell': 'Sell',
    'cchip.exchange': 'Exch.',
    'cchip.more': '+{n} more',
    // institutional / activist (SEC 13D/13G)
    'inst.title': 'Institutional & activist filings',
    'inst.subtitle': 'Recent SEC 13D/13G beneficial-ownership filings — who took a >5% stake in what.',
    'inst.disclaimer':
      'Public-domain SEC filings. 13D = active/activist stake (stronger signal); 13G = passive holding (e.g. index funds). Not investment advice.',
    'inst.all': 'All',
    'inst.activist': 'Activist (13D)',
    'inst.passive': 'Passive (13G)',
    'inst.filed': 'Filed',
    'inst.viewFiling': 'View filing',
    'inst.unknownFiler': 'Institutional filing',
    'inst.empty': 'No recent filings',
    'inst.emptySub': '13D/13G filings will appear here as they are disclosed.',
    'inst.footer': 'Source: SEC EDGAR 13D/13G filings (public domain). Not investment advice.',
    // IPO calendar
    'ipo.title': 'IPO calendar',
    'ipo.subtitle': 'US IPOs — recently priced, coming up, and newly filed. From the Nasdaq calendar.',
    'ipo.disclaimer':
      'Calendar data is delayed and for reference only. Dates, prices, and share counts are as filed and can change before pricing. Not investment advice or an offer to buy any security.',
    'ipo.upcoming': 'Upcoming',
    'ipo.priced': 'Recently priced',
    'ipo.filed': 'Newly filed',
    'ipo.colCompany': 'Company',
    'ipo.colExchange': 'Exchange',
    'ipo.colPrice': 'Price',
    'ipo.colShares': 'Shares',
    'ipo.colAmount': 'Amount',
    'ipo.colDate': 'Date',
    'ipo.colStatus': 'Status',
    'ipo.empty': 'No IPOs in this section',
    'ipo.emptySub': 'The calendar fills in as Nasdaq publishes new pricings and filings.',
    'ipo.emptyAll': 'No IPO data yet',
    'ipo.emptyAllSub':
      'The board is fetching the latest Nasdaq IPO calendar — check back shortly.',
    'ipo.footer': 'Source: Nasdaq IPO calendar (delayed, display-only). Not investment advice.',
    'ipo.updated': 'updated {t} ago',
    // screener
    'screen.title': 'Stock screener',
    'screen.subtitle': 'Filter the whole US market by price, daily % change, and session.',
    'screen.minPrice': 'Min price',
    'screen.maxPrice': 'Max price',
    'screen.minChange': 'Min change %',
    'screen.maxChange': 'Max change %',
    'screen.session': 'Session',
    'screen.sessionAll': 'Any',
    'screen.session.regular': 'Regular',
    'screen.session.pre': 'Pre-market',
    'screen.session.post': 'After-hours',
    'screen.session.overnight': 'Overnight',
    'screen.sort': 'Sort',
    'screen.sort.change_desc': 'Change ↓',
    'screen.sort.change_asc': 'Change ↑',
    'screen.sort.price_desc': 'Price ↓',
    'screen.sort.price_asc': 'Price ↑',
    'screen.apply': 'Apply',
    'screen.delayed': 'Delayed quotes (IEX), refreshed ~every 5 min.',
    'screen.empty': 'No matches',
    'screen.emptySub': 'Try widening your filters.',
    'screen.footer': 'Delayed market data (Alpaca IEX). Not investment advice.',
    'screen.colTicker': 'Ticker',
    'screen.colPrice': 'Price',
    'screen.colChange': 'Change',
    'screen.colSession': 'Session',
    // guru rail
    'guru.title': 'Guru-watch',
    'guru.subtitle':
      'What independent finance writers are publishing — and the tickers they name. Opinions for context, linked to the source.',
    'guru.empty': 'No guru posts yet',
    'guru.emptySub': 'The rail fills in as curated writers publish new pieces.',
    'guru.source': 'Source',
    'guru.footer':
      'Third-party opinions from public RSS feeds, shown for context. Not an endorsement. Not investment advice.',
    // wsb
    'wsb.title': 'WSB Trending',
    'wsb.hotList': 'Hot list',
    'wsb.mentions': 'mentions',
    'wsb.footer': 'Source: ApeWisdom · discussion volume, not advice.',
    // events
    'events.title': 'Events timeline',
    'events.subtitle':
      'Upcoming market-moving events — Fed decisions, key US data (CPI, jobs), and notable world events. For context, not advice.',
    'events.empty': 'No upcoming events',
    'events.emptySub': 'Check back soon.',
    'events.high': 'High',
    'events.all': 'All',
    'events.footer':
      'Sources: BLS, Federal Reserve + curated. Times in your local zone. Not investment advice.',
    // rate-cut odds (prediction markets) — folded into the Events page
    'ratecut.title': 'Rate-cut odds',
    'ratecut.blurb':
      'What prediction markets price for the Fed’s next move, by cut size.',
    'ratecut.updated': 'updated {t} ago',
    'ratecut.empty': 'No rate-cut odds yet',
    'ratecut.emptySub': 'Prediction-market odds will appear here once the feed is live.',
    'ratecut.footer': 'Prediction-market odds (Kalshi / Polymarket) — not investment advice.',
    // topics + shared states
    'topics.title': 'HOT TOPICS',
    'states.error': 'Something went wrong',
    'states.errorTitle': 'The wind dropped for a moment',
    'states.errorSub': "We couldn't load this feed. Check your connection and try again.",
    'states.retry': 'Try again',
    // hot list / leaderboards
    'hot.surging': 'Surging',
    'hot.blurbHot':
      'The most-discussed US stocks across Reddit right now — ranked by buzz and momentum.',
    'hot.blurbSurging':
      'Stocks whose chatter is accelerating fastest — the biggest 24h jumps in mentions, not just the loudest.',
    'hot.emptySub': 'The leaderboard refreshes every few minutes — check back shortly.',
    'hot.footer': 'Buzz via ApeWisdom (Reddit mentions). Not investment advice.',
    // auth
    'auth.titleSignup': 'Create your account',
    'auth.titleLogin': 'Welcome back',
    'auth.subSignup': 'Create a free account to unlock:',
    'auth.perkWatch': 'Track your own watchlist',
    'auth.perkDigest': 'A daily AI market briefing',
    'auth.perkAlerts': 'Price & earnings alerts',
    'auth.perkNotes': 'Private research notes',
    'auth.subLogin': 'Log in to your watchlist and saved links.',
    'auth.google': 'Continue with Google',
    'auth.or': 'or',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.busy': 'One moment…',
    'auth.createAccount': 'Create account',
    'auth.haveAccount': 'Already have an account?',
    'auth.noAccount': "Don't have an account?",
    'auth.pwTooShort': 'Password must be at least 6 characters.',
    'auth.genericError': 'Something went wrong.',
    'auth.checkEmail': 'Check your email to confirm your account, then log in.',
    // feed pages (News / Discussion)
    'feed.titleNews': 'Market news',
    'feed.titleFiltered': 'Filtered news',
    'feed.subNews': 'The latest headlines across the most-watched US stocks.',
    'feed.subDiscussion':
      'What people are saying about the most-watched US stocks — StockTwits, Bluesky and more.',
    'feed.subFiltered': 'Latest headlines about “{t}”.',
    'feed.allNews': '← All news',
    'feed.emptyFiltered': 'No recent news for this topic',
    'feed.emptyFilteredSub': 'Try another topic or see all news.',
    'feed.emptyNewsSub': 'Headlines will appear here as they break.',
    'feed.emptyChatterSub': 'Posts will show up here as they come in.',
    // board (Markets / Watchlist)
    'board.titleWatchlist': 'Your watchlist',
    'board.subWatchlist': 'Your stocks — prices, news and chatter in one place.',
    'board.subMarkets': 'Live prices, then the news and chatter across the market.',
    'board.addStock': 'Add a stock…',
    'board.loginTitle': 'Log in to see your watchlist',
    'board.loginSub': 'Track your own stocks and clip links from anywhere — free.',
    'board.emptyTitle': 'Your board is calm and empty',
    'board.emptySub': 'Add a ticker to follow its price, news and chatter.',
    'board.showFeed': 'Show news & discussion',
    'board.hideFeed': 'Hide news & discussion',
    'board.emptyNewsSub': 'Headlines about the stocks you follow will land here.',
    'board.emptyChatterSub': 'Posts from StockTwits and Reddit will show up here.',
    'board.loginToBuild': 'Log in to build your watchlist',
    'board.added': 'Added {t}',
    'board.already': '{t} is already on your watchlist',
    'board.addFailed': "Couldn't add {t}",
    'board.removed': 'Removed {t}',
    'board.undo': 'Undo',
    'board.removeFailed': "Couldn't remove {t}",
    'board.sortAdded': 'Added',
    'board.sortDefault': 'Default',
    'board.sortChange': 'Change',
    'board.sortAlpha': 'A–Z',
    'board.viewCards': 'Cards',
    'board.viewList': 'List',
    'footer.product': 'Product',
    'footer.account': 'Account',
    'footer.blurb': "Read every tick. See where the market's blowing.",
    'footer.copyright': '© 2026 Tickwind. Not investment advice.',
    'footer.tagline': 'Made for the curious investor.',
    'stock.yearRange': '52-wk range',
    'stock.waiting': 'Waiting for price…',
    'stock.loginAdd': 'Log in to track {t} and save links',
    'stock.loginAddSub': 'Keep a watchlist and clip posts from anywhere — free.',
    'stock.addWatch': 'Add to watchlist',
    'stock.onWatchlist': 'On your watchlist',
    'stock.removeWatch': 'Remove from watchlist',
    'stock.waitingPrice': 'Waiting for a price…',
    // pulse bar (detail-page buzz + sentiment chips)
    'pulse.buzz': 'Reddit buzz',
    'pulse.mentions24h': 'mentions / 24h',
    'pulse.rank': 'rank #{n}',
    'pulse.vs24h': 'vs 24h ago',
    'pulse.upvotes': 'upvotes',
    'pulse.sentiment': 'News sentiment',
    'pulse.across': 'across {n} recent articles',
    // k-line chart
    'kline.title': 'Price & indicators',
    'kline.o': 'O',
    'kline.h': 'H',
    'kline.l': 'L',
    'kline.c': 'C',
    'kline.tf.i': '1D',
    'kline.tf.5d': '5D',
    'kline.tf.d': 'D',
    'kline.tf.w': 'W',
    'kline.tf.m': 'M',
    'kline.tf.q': 'Q',
    'kline.tf.y': 'Y',
    'kline.empty': 'No price history yet',
    'kline.footer': 'Daily OHLC · MA/MACD/RSI computed locally. Not investment advice.',
    // comments
    'comments.tab': 'Comments',
    'comments.title': 'Community',
    'comments.subtitle': "What people are saying — across all stocks.",
    'comments.disclaimer':
      'User opinions — not investment advice, and not endorsed by Tickwind. Be civil; report anything abusive.',
    'comments.placeholder': 'Share your view…',
    'comments.post': 'Post',
    'comments.empty': 'No comments yet — be the first.',
    'comments.loginToPost': 'Log in to join the discussion.',
    'comments.report': 'Report',
    'comments.reported': 'Reported — thanks for flagging.',
    'comments.edit': 'Edit',
    'comments.save': 'Save',
    'comments.cancel': 'Cancel',
    'comments.edited': 'edited',
    'comments.mdHint': 'Markdown + $TICKER mentions supported',
    // settings
    'settings.signInTitle': 'Sign in to continue',
    'settings.signInSub': 'Your settings live with your account.',
    'settings.signedIn': 'Signed in',
    'settings.appearance': 'Appearance',
    'settings.subscription': 'Subscription',
    'settings.planPro': 'Tickwind Pro',
    'settings.planProSub': 'Full deep research + Pro features are unlocked.',
    'settings.planFree': 'Free plan',
    'settings.planFreeSub': 'Upgrade for the full AI Deep Research report and more.',
    'settings.manage': 'Manage',
    'settings.upgrade': 'Upgrade to Pro',
    'settings.theme': 'Theme',
    'settings.themeDark': 'Dark',
    'settings.themeLight': 'Light',
    'settings.themeHint': '— switch any time.',
    'stock.collecting': 'Gathering news & filings…',
    'stock.collectingSub':
      "First time we've tracked this one — the price is live; news, filings and discussion arrive shortly. This page updates on its own.",
    'stock.tabOverview': 'Overview',
    'stock.tabDetails': 'Details',
    'stock.tabResearch': 'Research',
    'stock.tabMoney': 'Filings & Money',
    'stock.tabNews': 'News & Discussion',
    'stock.tabMy': 'My',
    'stock.filings': 'Filings',
    'stock.savedLinks': 'Saved links',
    'stock.noNewsSub': 'New headlines will land here first.',
    'stock.noChatterSub': 'Posts from StockTwits, Bluesky and more will show up here.',
    'stock.noFilings': 'No recent filings',
    'stock.noFilingsSub': 'Filings appear here as soon as they hit SEC EDGAR.',
    'stock.noClips': 'No saved links yet',
    'stock.noClipsSub': 'Found something good elsewhere? Paste a link to clip it here.',
    'stock.clipPlaceholder': 'Paste an X / Xiaohongshu / TikTok link…',
    'stock.save': 'Save',
    'stock.notesPlaceholder': 'Add a private note or thesis…',
    'stock.noNotes': 'No notes yet',
    'stock.noNotesSub': 'Jot down your thesis, price targets, or anything to remember.',
    // notes page
    'notes.title': 'My notes',
    'notes.subtitle': 'Your private notes & opinions — across stocks and dates.',
    'notes.empty': 'No notes yet',
    'notes.emptySub': 'Write your first note below.',
    'notes.composePlaceholder': 'Write a note… (optionally tag a $TICKER)',
    'notes.add': 'Add note',
    'notes.delete': 'Delete',
    'notes.pin': 'Pin',
    'notes.unpin': 'Unpin',
    'notes.edit': 'Edit',
    'notes.save': 'Save',
    'notes.cancel': 'Cancel',
    'notes.edited': 'edited',
    'notes.list': 'List',
    'notes.calendar': 'Calendar',
    'notes.dayNote': 'Note for this day…',
    'notes.dayEmpty': 'No notes for this day.',
    'notes.pickDay': 'Pick a day',
    'notes.legendEvent': 'Event',
    'notes.legendNotes': 'Notes',
    // unified calendar shell tabs
    'cal.earnings': 'Earnings',
    'cal.macro': 'Macro',
    'cal.ipo': 'IPO',
    // personal hub (/me) tabs
    'me.title': 'My',
    'me.overview': 'Overview',
    'me.watchlist': 'Watchlist',
    'me.holdings': 'Holdings',
    'me.notes': 'Notes',
    'me.alerts': 'Alerts',
    // overnight digest (Overview tab)
    'digest.aiTitle': "Tonight's overview",
    'digest.stocksTitle': 'Your watchlist overnight',
    'digest.emptyTitle': 'No stocks yet',
    'digest.emptySub': 'Add stocks to your watchlist to get a personalized overnight report each morning.',
    'digest.emptyCta': 'Add stocks',
    'digest.error': "Couldn't load your overnight report. Try again later.",
    // discussion shell tabs
    'disc.discussion': 'Discussion',
    'disc.community': 'Community',
    'common.ago': 'ago',
    'common.showMore': 'Show more',
    'common.showLess': 'Show less',
    // indicator library
    'nav.indicators': 'Indicators',
    'ind.title': 'Indicator library',
    'ind.subtitle':
      'A browsable reference of {n} stock indicators — technical, fundamental and sentiment — with formulas, default parameters and how to read each one.',
    'ind.search': 'Search indicators — RSI, P/E, MACD…',
    'ind.allDomains': 'All',
    'ind.domain.technical': 'Technical',
    'ind.domain.fundamental': 'Fundamental',
    'ind.domain.sentiment': 'Sentiment',
    'ind.allPriorities': 'All tiers',
    'ind.priority.P0': 'Core',
    'ind.priority.P1': 'Advanced',
    'ind.priority.P2': 'Pro',
    'ind.tierP0': 'Core (P0)',
    'ind.tierP1': 'Advanced (P1)',
    'ind.tierP2': 'Pro (P2)',
    'ind.matches': '{n} of {total} indicators',
    'ind.formula': 'Formula',
    'ind.interpretation': 'How to read it',
    'ind.params': 'Default params',
    'ind.output': 'Output',
    'ind.inputs': 'Inputs',
    'ind.lib': 'Library',
    'ind.empty': 'No indicators match your filters',
    'ind.emptySub': 'Try a different keyword or clear the filters.',
    'ind.clear': 'Clear filters',
    'ind.collapse': 'Collapse',
    'ind.expand': 'Expand',
    'ind.footer':
      'Reference metadata only — public, well-known indicator definitions. Not investment advice.',
    'ind.coreNote': 'Highlighted indicators are the MVP core (P0).',
    // Per-indicator detail page (/indicators/{slug}).
    'ind3.crumbHome': 'Home',
    'ind3.crumbLibrary': 'Indicators',
    'ind3.appliesTo': 'Applies to: US stocks',
    'ind3.definition': 'Definition',
    'ind3.formula': 'Formula',
    'ind3.params': 'Default parameters',
    'ind3.interpretation': 'How to read it',
    'ind3.dataSource': 'Data source',
    'ind3.disclaimer': 'Public knowledge, not investment advice.',
    'ind3.related': 'Related indicators',
    'ind3.backToLibrary': 'Back to all indicators',
    'ind3.seeOnStock': 'See it computed on a stock',
    'ind3.metaInputs': 'Inputs',
    'ind3.metaOutput': 'Output',
    'ind3.metaLib': 'Library',
  },
  zh: {
    // top nav
    'nav.markets': '行情',
    'nav.hot': '热门',
    'nav.news': '新闻',
    'nav.opportunities': '机会',
    'nav.events': '大事件',
    'nav.congress': '国会交易',
    'nav.institutional': '机构举牌',
    'nav.smartMoney': '聪明钱',
    'nav.screen': '选股器',
    'nav.stocks': '全部股票',
    'nav.watchlist': '自选',
    'nav.notes': '笔记',
    'nav.community': '社区',
    'nav.ipo': '新股日历',
    'nav.calendar': '日历',
    'nav.discussion': '讨论',
    'nav.my': '我的',
    'nav.more': '更多',
    'nav.whatsnew': '更新',
    'nav.login': '登录',
    'nav.signup': '注册',
    'nav.search': '搜索股票…',
    'nav.myWatchlist': '我的自选',
    'nav.settings': '设置',
    'nav.signout': '退出登录',
    'nav.account': '账户菜单',
    'nav.signedIn': '已登录',
    'nav.menu': '菜单',
    // trading-session badge
    'session.pre': '盘前',
    'session.regular': '盘中',
    'session.post': '盘后',
    'session.overnight': '夜盘',
    'session.closed': '休市',
    // fundamentals card
    'fund.title': '财务',
    'fund.marketCap': '市值',
    'fund.pe': '市盈率',
    'fund.revenue': '营收',
    'fund.netIncome': '净利润',
    'fund.eps': '每股收益',
    'fund.pb': '市净率',
    'fund.loss': '亏损',
    'fund.source': '数据来源：SEC 申报',
    // per-stock indicators panel
    'ind2.title': '指标',
    'ind2.asOf': '数据截至 {d}',
    'ind2.domain.technical': '技术指标',
    'ind2.domain.fundamental': '基本面',
    'ind2.domain.sentiment': '情绪',
    'ind2.vix': 'VIX',
    'ind2.fearGreed': '恐慌贪婪',
    'ind2.learnMore': '在指标大全中查看',
    'ind2.empty': '—',
    // anonymous preview gate (sign in to see the full indicator set)
    'ind2.gate.title': '登录查看全部 {n} 项指标',
    'ind2.gate.sub': '当前为预览。登录即可解锁全部指标并自定义。',
    'ind2.gate.cta': '登录查看全部',
    // indicator picker (customize the selected indicators)
    'ind2.picker.customize': '自定义',
    'ind2.picker.title': '自定义指标',
    'ind2.picker.selected': '已选',
    'ind2.picker.search': '搜索指标…',
    'ind2.picker.allDomains': '全部',
    'ind2.picker.add': '添加',
    'ind2.picker.remove': '移除',
    'ind2.picker.reset': '恢复默认',
    'ind2.picker.count': '已选 {n} 个',
    'ind2.picker.empty': '尚未选择指标 —— 在下方添加。',
    'ind2.picker.noMatch': '没有匹配的指标。',
    'ind2.picker.moveUp': '上移',
    'ind2.picker.moveDown': '下移',
    'ind2.picker.close': '关闭',
    // signals (deterministic posture signals derived from the computed indicators)
    'signals.title': '信号',
    'signals.asOf': '截至 {d}',
    'signals.empty': '当前暂无活跃信号。',
    'signals.dir.bullish': '看多',
    'signals.dir.bearish': '看空',
    'signals.dir.neutral': '中性',
    'signals.trust': '每个信号都是对已算出指标的确定性规则 —— 绝非投资建议或目标价。',
    'signals.locked.title': '更多信号需 Pro',
    'signals.locked.body': 'Pro 解锁完整信号集 —— 每条都是对已算出数字的透明规则,绝不编造、绝非建议。',
    'signals.locked.cta': '再解锁 {n} 条',
    // earnings
    'quote.lastTrade': '最后成交 {t}前 · {src}',
    'quote.lastTradeNow': '最后成交 刚刚 · {src}',
    'options.title': '期权概览',
    'options.delayed': '数据延迟15分钟 · Cboe',
    'options.pcVol': '沽购比(量)',
    'options.pcOI': '沽购比(持仓)',
    'options.maxPain': '最大痛点',
    'options.topOI': '未平仓龙虎榜',
    'options.kind': '类型',
    'options.call': '看涨',
    'options.put': '看跌',
    'options.strike': '行权价',
    'options.expiry': '到期',
    'options.oi': '未平仓',
    'options.vol': '成交',
    'options.iv': '隐波',
    // unusual options board
    'nav.unusual': '期权异动',
    'unusual.title': '期权异动榜',
    'unusual.subtitle': '今日全市场成交最活跃的期权合约 —— 看清资金正在涌入哪里。',
    'unusual.empty': '暂无异动数据 —— 正在扫描全市场。',
    'unusual.ticker': '代码',
    'unusual.volOI': '量比',
    // 13F whale holdings
    '13f.tab': '大佬持仓',
    '13f.title': '大佬持仓 · 13F',
    '13f.subtitle': '知名基金经理上季度持仓 —— 巴菲特、伯里、阿克曼、李录等，来自 SEC 13F 申报。',
    '13f.disclaimer': '13F 持仓在季度结束后约 45 天才披露，因此是历史快照 —— 仅含多头(不含做空/期权)，来自 SEC 公开数据。非投资建议。',
    '13f.asOf': '截至',
    '13f.empty': '暂无持仓数据',
    '13f.emptySub': '正在抓取最新 13F 申报 —— 稍后再来看看。',
    '13f.footer': '数据来源：SEC 13F-HR 申报(公有领域)；CUSIP→代码经 OpenFIGI 映射。非投资建议。',
    '13f.colStock': '股票',
    '13f.colValue': '市值',
    '13f.colPct': '占比',
    '13f.colChange': '环比',
    '13f.change.new': '新建仓',
    '13f.change.add': '加仓',
    '13f.change.trim': '减仓',
    '13f.change.hold': '持有',
    'whales.title': '机构大佬持仓',
    'whales.weight': '占组合 {w}%',
    'whales.more': '另有 {n} 家',
    'brief.title': '盘前晨报',
    'brief.empty': '今日晨报尚未生成，开盘前来看看吧。',
    'ai.title': 'AI 速览',
    'ai.badge': 'AI 生成',
    'ai.loading': '正在解读最新动态…',
    'ai.disclaimer': '由 AI 基于近期新闻与社区讨论生成 · 仅供参考 · 不构成投资建议',
    // 异动解读卡片：对显著（涨跌幅 >= 5%）单日异动的、有证据支撑的解读。
    // 涨跌幅由后端计算，文字为对冲性推测。
    'move.title': '为何异动？',
    'move.aiBadge': 'AI 生成',
    'move.evidence': '可能相关',
    'move.type.news': '新闻',
    'move.type.filing': '公告',
    'move.type.insider': '内部人买入',
    'move.disclaimer': 'AI 生成 · 仅供参考 · 非投资建议。涨跌幅由数据计算，解读为对冲性推测，非确定原因。',
    'move.disclaimerData': '涨跌幅由数据计算 · 仅供参考 · 非投资建议。暂无确定催化原因。',
    // 8-K 重大事件公告 + AI 摘要卡片
    'filings.title': '重大事件公告 (8-K)',
    'filings.aiBadge': 'AI 摘要',
    'filings.amendment': '修订',
    'filings.viewSource': '查看 SEC 原文',
    'filings.reportDate': '事件日期',
    'filings.empty': '近期无重大公告',
    'filings.source': '数据来源：SEC EDGAR',
    'filings.asOf': '截至',
    'filings.disclaimer': '公告事实（类型、日期、事项类别）来自 SEC EDGAR；摘要由 AI 生成，仅供参考，非投资建议。',
    // Insider-activity (Form 4 buy/sell) timeline card
    'insider.title': '内部人交易 (Form 4)',
    'insider.buy': '买入',
    'insider.sell': '卖出',
    'insider.planned': '10b5-1 计划',
    'insider.plannedTitle': '依据预先设定的 Rule 10b5-1 交易计划卖出——信号意义弱于自主决定的卖出。',
    'insider.shares': '股',
    'insider.atPrice': '@',
    'insider.viewSource': '查看 SEC 原文',
    'insider.empty': '近期无内部人交易',
    'insider.source': '数据来源：SEC EDGAR Form 4',
    'insider.asOf': '截至',
    'insider.delay': 'Form 4 于交易后 2 个工作日内申报。',
    'insider.net': '净额',
    'insider.buys': '买入',
    'insider.sells': '卖出',
    // R2 深度研报（界面文案中英默认英文；报告正文按设计为中文）
    'research.tab': '深度研报',
    'research.title': '深度研报',
    'research.loading': '正在生成研报…',
    'research.asOf': '截至 {d}',
    'research.label': 'AI 生成 · 数字来自公开数据 · 非投资建议',
    'research.dataOnly': 'AI 摘要暂未启用 —— 仅展示数据。',
    'research.sources': '数据来源',
    'research.bull': '看多视角',
    'research.bear': '看空视角',
    'research.insufficient': '数据不足',
    'research.empty': '该标的暂无数据。',
    // 深度研报(需登录解锁)视图 + AI 速览入口按钮
    'deep.entry': '深度研报',
    'deep.title': 'AI 深度研报',
    'deep.subtitle': '{t} 的来源可溯、AI 撰写的分析师研报。',
    'deep.trust': '每个数字都源自公开披露 —— AI 只负责分析,绝不编造任何数字。',
    'deep.back': '返回 {t}',
    'deep.overview': '核心摘要',
    'deep.generating': '正在生成深度研报…',
    'deep.generatingSub': '更强的模型正在研读公开数据,约需 10–60 秒。',
    'deep.proseGenerating': '正在生成深度分析…',
    'deep.proseSlow': '生成较慢,点此重试',
    'deep.proseQuota': '本月深度研报已用完',
    'deep.facts': '关键数据',
    'deep.factsCol': '指标',
    'deep.valueCol': '数值',
    'deep.sourceCol': '来源 · 截至',
    'deep.priceChart': '股价(近 5 年)',
    'deep.exportPdf': '导出 PDF',
    'deep.gate.title': '登录解锁 AI 深度研报',
    'deep.gate.body': '{t} 的更深度、来源可溯的分析师研报 —— 涵盖估值 / 基本面 / 技术 / 资金面 / 情绪面多个板块,每个数字均来自公开数据。登录会员免费。',
    'deep.gate.cta': '登录以继续',
    'deep.gate.preview': '预览',
    'deep.gate.previewNote': '以下为公开研报预览 —— 登录查看完整深度研报。',
    'deep.quota.title': '本月深度研报已用完',
    'deep.quota.body': '您本月的深度研报生成额度已用完,下月初重置。也可以打开本月已生成研报的股票(已生成的免费查看)。',
    'deep.error.title': '深度研报加载失败',
    'deep.error.retry': '重试',
    'deep.locked.section': '升级 Tickwind Pro 解锁此板块。',
    'deep.paywall.title': '解锁完整深度研报',
    'deep.paywall.body': '你正在看免费预览——概览 + 一个板块。Tickwind Pro 解锁全部板块、多空双向解读、按需刷新和 PDF 导出。每个数字依旧来自公开数据有出处——Pro 只是为你打开完整阅读。',
    'deep.paywall.cta': '查看 Pro 方案',
    'pro.title': 'Tickwind Pro',
    'pro.subtitle': '完整 AI 深度研报及更多——每个数字依旧来自公开数据、有出处。',
    'pro.annual': '年付',
    'pro.monthly': '月付',
    'pro.save': '省 ~36%',
    'pro.mo': '月',
    'pro.billedAnnually': '按 $99 / 年计费',
    'pro.billedMonthly': '按月计费',
    'pro.feat1': 'AI 深度研报的全部板块——估值、基本面、技术面、资金面、情绪面',
    'pro.feat2': '每支股票完整的多空双向解读',
    'pro.feat3': '随时按需刷新最新数据',
    'pro.feat4': '带品牌的 PDF 与分享图导出',
    'pro.trust': 'AI 只负责分析、从不编造数字——每个数字都源自公开披露、有出处。',
    'pro.cta': '订阅',
    'pro.ctaLogin': '登录后订阅',
    'pro.err': '无法发起结账——请重试。',
    'pro.cancel': '随时可取消。',
    'pro.disclaimer': 'Tickwind 提供基于公开数据的客观梳理，非投资建议。',
    'pro.success.title': '你已是 Pro 🎉',
    'pro.success.body': '订阅已生效——完整深度研报与 Pro 功能已解锁。',
    'pro.success.cta': '开始探索',
    'short.title': '空头压力',
    'short.dtc': '回补天数',
    'short.qty': '空头仓位',
    'short.risk': '轧空风险',
    'short.asof': '截至 {d}',
    // daily short-volume facet (finrashvol)
    'short.todayPct': '今日做空',
    'short.dailyTrend': '做空占比走势',
    'short.dailyAsof': '每日 · 截至 {d}',
    // market-wide today's-short-volume board (one /hot tab)
    'shortvol.tab': '做空榜',
    'shortvol.title': '今日做空榜',
    'shortvol.blurb': '今日做空成交占比最高的美股 —— 一个高频观察盘中空头压力的视角。',
    'shortvol.colSymbol': '代码',
    'shortvol.colShortPct': '做空占比',
    'shortvol.colVolume': '成交量',
    'shortvol.empty': '暂无做空数据',
    'shortvol.emptySub': '今日 FINRA 做空成交数据到位后，榜单会自动填充。',
    'shortvol.asof': '截至 {d}',
    'shortvol.footer': '数据来源：FINRA 做空成交量。非投资建议。',
    // fear & greed index (home hub chip)
    'sentiment.title': '恐贪指数',
    'sentiment.extremeFear': '极度恐惧',
    'sentiment.fear': '恐惧',
    'sentiment.neutral': '中性',
    'sentiment.greed': '贪婪',
    'sentiment.extremeGreed': '极度贪婪',
    'sentiment.components': '指数构成',
    'sentiment.trend': '近期走势',
    'sentiment.trendDays': '{n} 天',
    'sentiment.updated': '{t}前更新',
    'sentiment.footer': '潮汐自有综合指数。方法论 —— 非投资建议。',
    // macro strip — U.S. Treasury yield curve (2s10s recession signal)
    'macro.title': '美国国债收益率',
    'macro.spread': '2s10s 利差',
    'macro.inverted': '倒挂',
    'macro.normal': '正常',
    'macro.invertedHint': '收益率曲线倒挂（10年期 < 2年期）—— 经典的衰退预警信号',
    'macro.normalHint': '收益率曲线正常向上（10年期 > 2年期）',
    'macro.updated': '数据日期 {t}',
    'crypto.title': '加密市场情绪',
    'crypto.extremeFear': '极度恐惧',
    'crypto.fear': '恐惧',
    'crypto.neutral': '中性',
    'crypto.greed': '贪婪',
    'crypto.extremeGreed': '极度贪婪',
    'crypto.updated': '数据日期 {t}',
    // share card ("propagation organ") — save/share a branded image card
    'share.save': '保存图片',
    'share.aria': '在新标签页打开可分享的图片卡',
    'earnings.next': '下次财报',
    'earnings.estEps': '预期EPS',
    'earnings.bmo': '盘前',
    'earnings.amc': '盘后',
    'earnings.dmh': '盘中',
    'nav.earnings': '财报',
    'news.aiTranslated': 'AI 译',
    'earnings.calTitle': '财报日历',
    'earnings.calSubtitle': '美股即将公布的财报，按日分组 · 预期 vs 实际 EPS',
    'earnings.calEmpty': '暂无即将公布的财报',
    'earnings.calEmptySub': '稍后再来——日历会全天更新。',
    'earnings.est': '预期',
    'earnings.act': '实际',
    // alerts
    'alerts.title': '提醒',
    'alerts.kind': '条件',
    'alerts.priceAbove': '价格高于',
    'alerts.priceBelow': '价格低于',
    'alerts.pctMove': '日内波动',
    'alerts.newFiling': '新 SEC 申报',
    'alerts.threshold': '价格',
    'alerts.percent': '百分比',
    'alerts.add': '添加提醒',
    'alerts.hint': '我们会监控这只股票，满足条件时为你标记。',
    'alerts.empty': '这只股票还没有提醒。',
    'alerts.delete': '删除提醒',
    'alerts.deliveryNote': '触发的提醒会在站内显示。（推送通知开发中。）',
    'alerts.triggered': '已触发',
    'nav.alerts': '提醒',
    'alerts.centerTitle': '提醒中心',
    'alerts.centerSubtitle': '你所有股票的价格与事件提醒——已触发和监控中，一处尽览。',
    'alerts.centerEmpty': '还没有提醒。在任意股票页添加一个吧。',
    'alerts.loginToView': '登录后查看你的提醒。',
    'alerts.active': '监控中',
    'alerts.rearm': '重新激活',
    'alerts.rearmed': '提醒已重新激活',
    // home hub
    'home.title': '今日市场',
    'home.subtitle': '实时价格，以及全市场的趋势、新闻与讨论 —— 一站式呈现。',
    'home.indices': '美股大盘',
    'home.hotTopics': '热点话题',
    'search.title': '搜索',
    'search.hint': '在上方输入股票代码或公司名称进行搜索。',
    'search.for': '“{q}” 的搜索结果',
    'search.searching': '搜索中…',
    'search.empty': '没有匹配 “{q}” 的标的。',
    'search.emptyHint': '可能是我们尚未收录的粉单 / OTC 代码 —— 你仍可直接打开。',
    'search.gotoAnyway': '直接打开 {q}',
    'topic.heating': '升温中',
    'topic.sub': '与“{t}”相关的股票与新闻',
    'topic.stocks': '相关股票',
    'topic.news': '相关新闻',
    'topic.empty': '未找到该话题',
    'topic.emptySub': '该话题当前不在热门中。',
    'topic.noNews': '暂无相关新闻',
    'topic.noNewsSub': '稍后再来看看。',
    'holdings.title': '持仓',
    'holdings.shares': '股数',
    'holdings.avgCost': '成本价',
    'holdings.value': '市值',
    'holdings.pl': '盈亏',
    'holdings.save': '保存',
    'holdings.remove': '移除',
    'holdings.empty': '尚无持仓 —— 在上方填入股数与成本价。',
    'holdings.hint': '仅自己可见。市值与盈亏随实时价格更新。',
    'nav.portfolio': '持仓组合',
    'portfolio.title': '持仓组合',
    'portfolio.subtitle': '你的持仓，实时估值。',
    'portfolio.total': '总市值',
    'portfolio.totalCost': '总成本',
    'portfolio.dayPL': '当日盈亏',
    'portfolio.totalPL': '总盈亏',
    'portfolio.allocation': '持仓占比',
    'portfolio.allocShort': '占',
    'portfolio.ticker': '代码',
    'portfolio.price': '现价',
    'portfolio.empty': '尚无持仓',
    'portfolio.emptySub': '在任意股票页的"持仓"标签添加持仓。',
    'portfolio.someUnpriced': '部分持仓暂无实时价格，未计入总计。',
    'portfolio.disclaimer': '仅用于记录，非投资建议；总计按各币种名义直接相加。',
    'mod.hotStocks': '热门股票',
    'mod.opportunity': '机会榜',
    'mod.guru': '大V观点',
    'mod.news': '新闻',
    'mod.discussion': '讨论',
    'mod.fullBoard': '完整榜单',
    'mod.seeAll': '查看全部',
    'mod.showMore': '展开更多 {n} 条',
    'mod.showLess': '收起',
    'mkt.allStocks': '全部股票',
    'mod.moreNews': '更多新闻',
    'mod.joinIn': '参与讨论',
    'mod.noData': '暂无数据',
    'mod.noSignals': '暂无信号',
    'mod.noPosts': '暂无内容',
    'mod.noNews': '暂无新闻',
    'mod.noChatter': '暂无讨论',
    // opportunity board
    'opp.title': '机会榜',
    'opp.subtitle': '内部人正在公开市场买入的美国小盘股 —— 来自 SEC Form 4 申报。',
    'opp.disclaimer':
      '榜单由数据信号（内部人公开买入）生成，并非推荐；列入不代表评级或买入建议。小盘股可能波动较大、流动性较差。非投资建议。',
    'opp.empty': '暂无内部人买入信号',
    'opp.emptySub': '随着近期 SEC Form 4 公开买入申报陆续公布，榜单会逐步填充。',
    'opp.smallCap': '小盘股',
    'opp.viewFiling': '查看 SEC 申报',
    'opp.footer': '内部人数据来自公开的 SEC EDGAR 申报。非投资建议。',
    // congress
    'congress.title': '国会交易',
    'congress.subtitle': '美国众议院议员最新股票交易披露（定期交易报告 PTR）。',
    'congress.disclaimer':
      '美国众议院官方金融披露（众议院书记官公开数据）。反映披露申报时间，非实时交易。非投资建议。',
    'congress.filed': '申报于',
    'congress.viewFiling': '查看官方文件',
    'congress.empty': '暂无最新披露',
    'congress.emptySub': '议员定期交易报告（PTR）申报后将在此显示。',
    'congress.footer': '数据来源：美国众议院书记官金融披露（公有领域）。非投资建议。',
    // congress member detail page (pSEO)
    'member.eyebrow': '国会交易',
    'member.tradesTitle': '披露交易',
    'member.colDate': '日期',
    'member.colType': '方向',
    'member.colAsset': '资产',
    'member.colAmount': '金额区间',
    'member.owner.self': '本人',
    'member.owner.spouse': '配偶',
    'member.owner.joint': '共同',
    'member.owner.child': '子女',
    'member.type.purchase': '买入',
    'member.type.sale': '卖出',
    'member.type.exchange': '换股',
    'member.empty': '暂无披露交易',
    'member.emptySub': '该议员目前还没有定期交易报告（PTR）在档。',
    'member.disclaimer':
      '公开数据（美国众议院书记官）。申报最多滞后 45 天，且仅标注金额区间 —— 非实时交易，亦非投资建议。',
    'member.footer': '数据来源：美国众议院书记官金融披露（公有领域）。非投资建议。',
    // 跟单模拟（历史复盘）—— 议员页
    'sim.title': '跟单模拟',
    'sim.subtitle':
      '历史复盘：在每笔披露买入的“披露日收盘价”虚拟买入并持有至今，对比同日买入 SPY。',
    'sim.vs': 'vs SPY',
    'sim.statSuffix': '模拟跟单 vs SPY',
    'sim.member': '跟单',
    'sim.spy': 'SPY',
    'sim.method': '方法',
    'sim.methodBody':
      '每笔披露的买入按“披露日收盘价”等权虚拟买入（披露最多滞后约 45 天，这是跟随者真正能买到的价格）；持有至今，或在后续披露卖出的“披露日收盘价”平仓。基准 = 同等金额、于每个买入日买入 SPY 并持有至今。仅用日线收盘价，未计费用与税。',
    'sim.notReal':
      '模拟历史复盘 —— 非真实收益，非投资建议。等权计算，基于滞后于真实交易的公开披露。',
    'sim.coverage': '覆盖率',
    'sim.coverageBody': '已模拟 {used} 笔 · 跳过 {skipped} 笔（无价格历史）',
    'sim.windowNote': '区间：{start} → 至今（{months} 个月）',
    'sim.insufficient': '数据不足以回测',
    'sim.insufficientSub': '该议员暂无可定价的披露买入记录，无法进行跟单复盘。',
    // congress chip on the stock detail page (members' recent trades in a ticker)
    'cchip.title': '议员近期买卖',
    'cchip.buy': '买入',
    'cchip.sell': '卖出',
    'cchip.exchange': '换股',
    'cchip.more': '另有 {n} 笔',
    // institutional / activist (SEC 13D/13G)
    'inst.title': '机构 / 举牌',
    'inst.subtitle': '近期 SEC 13D/13G 举牌披露 —— 谁对谁建立了 >5% 的持仓。',
    'inst.disclaimer':
      'SEC 公开申报。13D=主动举牌(信号更强)；13G=被动持有(如指数基金)。非投资建议。',
    'inst.all': '全部',
    'inst.activist': '主动举牌 (13D)',
    'inst.passive': '被动 (13G)',
    'inst.filed': '申报于',
    'inst.viewFiling': '查看文件',
    'inst.unknownFiler': '机构申报',
    'inst.empty': '暂无最新举牌',
    'inst.emptySub': '13D/13G 申报披露后将显示在此。',
    'inst.footer': '数据来源：SEC EDGAR 13D/13G 申报（公有领域）。非投资建议。',
    // IPO calendar
    'ipo.title': '美股 IPO 日历',
    'ipo.subtitle': '美股新股 —— 近期已定价、即将上市、新近申报。来自 Nasdaq 日历。',
    'ipo.disclaimer':
      '日历数据有延迟，仅供参考。日期、价格与发行股数均为申报值，定价前可能变动。非投资建议，亦非任何证券的购买要约。',
    'ipo.upcoming': '即将上市',
    'ipo.priced': '近期已定价',
    'ipo.filed': '新近申报',
    'ipo.colCompany': '公司',
    'ipo.colExchange': '交易所',
    'ipo.colPrice': '价格',
    'ipo.colShares': '发行股数',
    'ipo.colAmount': '募资金额',
    'ipo.colDate': '日期',
    'ipo.colStatus': '状态',
    'ipo.empty': '该分组暂无新股',
    'ipo.emptySub': '随着 Nasdaq 公布新的定价与申报，日历会逐步填充。',
    'ipo.emptyAll': '暂无 IPO 数据',
    'ipo.emptyAllSub': '正在抓取最新的 Nasdaq IPO 日历 —— 稍后再来看看。',
    'ipo.footer': '数据来源：Nasdaq IPO 日历（延迟、仅供展示）。非投资建议。',
    'ipo.updated': '{t}前更新',
    // screener
    'screen.title': '选股器',
    'screen.subtitle': '按价格、当日涨跌幅、交易时段筛选全美股。',
    'screen.minPrice': '最低价',
    'screen.maxPrice': '最高价',
    'screen.minChange': '最小涨跌%',
    'screen.maxChange': '最大涨跌%',
    'screen.session': '时段',
    'screen.sessionAll': '全部',
    'screen.session.regular': '盘中',
    'screen.session.pre': '盘前',
    'screen.session.post': '盘后',
    'screen.session.overnight': '夜盘',
    'screen.sort': '排序',
    'screen.sort.change_desc': '涨跌 ↓',
    'screen.sort.change_asc': '涨跌 ↑',
    'screen.sort.price_desc': '价格 ↓',
    'screen.sort.price_asc': '价格 ↑',
    'screen.apply': '应用',
    'screen.delayed': '行情延迟（IEX），约每 5 分钟刷新。',
    'screen.empty': '无匹配结果',
    'screen.emptySub': '尝试放宽筛选条件。',
    'screen.footer': '行情数据延迟（Alpaca IEX）。非投资建议。',
    'screen.colTicker': '代码',
    'screen.colPrice': '价格',
    'screen.colChange': '涨跌',
    'screen.colSession': '时段',
    // guru rail
    'guru.title': '大V观点',
    'guru.subtitle': '独立财经作者在写什么 —— 以及他们提到的股票。观点仅供参考，附原文链接。',
    'guru.empty': '暂无大V内容',
    'guru.emptySub': '随着精选作者发布新文章，这里会陆续更新。',
    'guru.source': '原文',
    'guru.footer': '来自公开 RSS 的第三方观点，仅供参考，不代表认可。非投资建议。',
    // wsb
    'wsb.title': 'WSB 热议',
    'wsb.hotList': '完整榜单',
    'wsb.mentions': '次提及',
    'wsb.footer': '来源：ApeWisdom · 讨论热度，非投资建议。',
    // events
    'events.title': '大事件时间线',
    'events.subtitle': '即将到来的市场大事件 —— 美联储决议、关键美国数据（CPI、非农）以及重要世界事件。仅供参考，非投资建议。',
    'events.empty': '暂无即将到来的事件',
    'events.emptySub': '稍后再来看看。',
    'events.high': '重要',
    'events.all': '全部',
    'events.footer': '来源：BLS、美联储 + 精选。时间按你的本地时区显示。非投资建议。',
    // rate-cut odds (prediction markets) — folded into the Events page
    'ratecut.title': '降息概率',
    'ratecut.blurb': '预测市场对美联储下一步动作（按降息幅度）的定价。',
    'ratecut.updated': '{t}前更新',
    'ratecut.empty': '暂无降息概率',
    'ratecut.emptySub': '预测市场数据上线后将显示在这里。',
    'ratecut.footer': '预测市场赔率（Kalshi / Polymarket）—— 非投资建议。',
    // topics + shared states
    'topics.title': '热点话题',
    'states.error': '出错了',
    'states.errorTitle': '信号中断了一下',
    'states.errorSub': '未能加载此内容，请检查网络连接后重试。',
    'states.retry': '重试',
    // hot list / leaderboards
    'hot.surging': '飙升',
    'hot.blurbHot': '当前 Reddit 上讨论最多的美股 —— 按热度与势头排名。',
    'hot.blurbSurging': '讨论热度加速最快的股票 —— 24 小时提及增幅最大，而非单纯最热闹的。',
    'hot.emptySub': '榜单每几分钟刷新一次 —— 稍后再来看看。',
    'hot.footer': '热度数据来自 ApeWisdom（Reddit 提及）。非投资建议。',
    // auth
    'auth.titleSignup': '创建账户',
    'auth.titleLogin': '欢迎回来',
    'auth.subSignup': '创建免费账户,即可解锁:',
    'auth.perkWatch': '自选股追踪',
    'auth.perkDigest': '每日 AI 中文晨报',
    'auth.perkAlerts': '价格 & 财报提醒',
    'auth.perkNotes': '私人投资笔记',
    'auth.subLogin': '登录以查看你的自选与收藏。',
    'auth.google': '使用 Google 继续',
    'auth.or': '或',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.busy': '请稍候…',
    'auth.createAccount': '创建账户',
    'auth.haveAccount': '已有账户？',
    'auth.noAccount': '还没有账户？',
    'auth.pwTooShort': '密码至少需要 6 位。',
    'auth.genericError': '出错了。',
    'auth.checkEmail': '请查收邮件以确认账户，然后登录。',
    // feed pages
    'feed.titleNews': '市场新闻',
    'feed.titleFiltered': '筛选新闻',
    'feed.subNews': '热门美股的最新头条。',
    'feed.subDiscussion': '人们在 StockTwits、Bluesky 等平台讨论热门美股的内容。',
    'feed.subFiltered': '关于「{t}」的最新头条。',
    'feed.allNews': '← 全部新闻',
    'feed.emptyFiltered': '该话题暂无近期新闻',
    'feed.emptyFilteredSub': '换个话题，或查看全部新闻。',
    'feed.emptyNewsSub': '有新头条时会显示在这里。',
    'feed.emptyChatterSub': '有新讨论时会显示在这里。',
    // board
    'board.titleWatchlist': '我的自选',
    'board.subWatchlist': '你的自选股 —— 价格、新闻与讨论一站式呈现。',
    'board.subMarkets': '实时价格，以及全市场的新闻与讨论。',
    'board.addStock': '添加股票…',
    'board.loginTitle': '登录以查看你的自选',
    'board.loginSub': '随时随地跟踪你的自选股与收藏链接 —— 免费。',
    'board.emptyTitle': '你的看板还空着',
    'board.emptySub': '添加一只股票，跟踪它的价格、新闻与讨论。',
    'board.showFeed': '显示新闻与讨论',
    'board.hideFeed': '隐藏新闻与讨论',
    'board.emptyNewsSub': '你关注的股票的新闻会显示在这里。',
    'board.emptyChatterSub': '来自 StockTwits 和 Reddit 的讨论会显示在这里。',
    'board.loginToBuild': '登录以创建你的自选',
    'board.added': '已添加 {t}',
    'board.already': '{t} 已在你的自选中',
    'board.addFailed': '添加 {t} 失败',
    'board.removed': '已移除 {t}',
    'board.undo': '撤销',
    'board.removeFailed': '移除 {t} 失败',
    'board.sortAdded': '添加顺序',
    'board.sortDefault': '默认',
    'board.sortChange': '涨跌幅',
    'board.sortAlpha': '字母',
    'board.viewCards': '卡片',
    'board.viewList': '列表',
    'footer.product': '产品',
    'footer.account': '账户',
    'footer.blurb': '读懂每一次跳动，看清市场风向。',
    'footer.copyright': '© 2026 Tickwind。非投资建议。',
    'footer.tagline': '为好奇的投资者而做。',
    'stock.yearRange': '52周区间',
    'stock.waiting': '正在等待价格…',
    'stock.loginAdd': '登录以关注 {t} 并保存链接',
    'stock.loginAddSub': '随时随地维护自选股、收藏帖子 —— 免费。',
    'stock.addWatch': '加入自选',
    'stock.onWatchlist': '已在自选中',
    'stock.removeWatch': '移出自选',
    'stock.waitingPrice': '正在等待价格…',
    // pulse bar
    'pulse.buzz': 'Reddit 热度',
    'pulse.mentions24h': '次提及 / 24h',
    'pulse.rank': '排名 #{n}',
    'pulse.vs24h': '较 24h 前',
    'pulse.upvotes': '次赞',
    'pulse.sentiment': '新闻情绪',
    'pulse.across': '基于 {n} 篇近期文章',
    // k-line chart
    'kline.title': 'K线与指标',
    'kline.o': '开',
    'kline.h': '高',
    'kline.l': '低',
    'kline.c': '收',
    'kline.tf.i': '分时',
    'kline.tf.5d': '5日',
    'kline.tf.d': '日',
    'kline.tf.w': '周',
    'kline.tf.m': '月',
    'kline.tf.q': '季',
    'kline.tf.y': '年',
    'kline.empty': '暂无价格历史',
    'kline.footer': '日K线 · MA/MACD/RSI 本地计算。非投资建议。',
    // comments
    'comments.tab': '评论',
    'comments.title': '社区讨论',
    'comments.subtitle': '大家都在聊什么 —— 跨所有股票。',
    'comments.disclaimer': '用户观点 —— 非投资建议，不代表 Tickwind 立场。请文明发言；如有不当内容请举报。',
    'comments.placeholder': '分享你的看法…',
    'comments.post': '发布',
    'comments.empty': '还没有评论 —— 来抢沙发。',
    'comments.loginToPost': '登录后参与讨论。',
    'comments.report': '举报',
    'comments.reported': '已举报，谢谢反馈。',
    'comments.edit': '编辑',
    'comments.save': '保存',
    'comments.cancel': '取消',
    'comments.edited': '已编辑',
    'comments.mdHint': '支持 Markdown 和 $股票代码 提及',
    // settings
    'settings.signInTitle': '请先登录',
    'settings.signInSub': '你的设置与账户绑定。',
    'settings.signedIn': '已登录',
    'settings.appearance': '外观',
    'settings.subscription': '订阅',
    'settings.planPro': 'Tickwind Pro',
    'settings.planProSub': '完整深度研报与 Pro 功能已解锁。',
    'settings.planFree': '免费版',
    'settings.planFreeSub': '升级解锁完整 AI 深度研报及更多。',
    'settings.manage': '管理',
    'settings.upgrade': '升级 Pro',
    'settings.theme': '主题',
    'settings.themeDark': '深色',
    'settings.themeLight': '浅色',
    'settings.themeHint': '—— 随时可切换。',
    'stock.collecting': '正在收集新闻与申报…',
    'stock.collectingSub': '这是我们首次收录该股票 —— 价格已就绪，新闻、申报与讨论稍后到位，页面会自动更新。',
    'stock.tabOverview': '概览',
    'stock.tabDetails': '详情',
    'stock.tabResearch': '深度研报',
    'stock.tabMoney': '申报与资金',
    'stock.tabNews': '新闻与讨论',
    'stock.tabMy': '我的',
    'stock.filings': '申报',
    'stock.savedLinks': '收藏链接',
    'stock.noNewsSub': '新的相关新闻会最先出现在这里。',
    'stock.noChatterSub': '来自 StockTwits、Bluesky 等的讨论会显示在这里。',
    'stock.noFilings': '暂无近期申报',
    'stock.noFilingsSub': '申报一旦出现在 SEC EDGAR，就会显示在这里。',
    'stock.noClips': '还没有收藏链接',
    'stock.noClipsSub': '在别处看到好内容？粘贴链接即可收藏到这里。',
    'stock.clipPlaceholder': '粘贴 X / 小红书 / TikTok 链接…',
    'stock.save': '保存',
    'stock.notesPlaceholder': '写下你的备注或观点…',
    'stock.noNotes': '还没有笔记',
    'stock.noNotesSub': '记下你的投资逻辑、目标价，或任何想记住的内容。',
    // notes page
    'notes.title': '我的笔记',
    'notes.subtitle': '你的私人笔记与观点 —— 跨股票与日期。',
    'notes.empty': '还没有笔记',
    'notes.emptySub': '在下方写下你的第一条笔记。',
    'notes.composePlaceholder': '写一条笔记…（可选：标注 $股票代码）',
    'notes.add': '添加笔记',
    'notes.delete': '删除',
    'notes.pin': '置顶',
    'notes.unpin': '取消置顶',
    'notes.edit': '编辑',
    'notes.save': '保存',
    'notes.cancel': '取消',
    'notes.edited': '已编辑',
    'notes.list': '列表',
    'notes.calendar': '日历',
    'notes.dayNote': '当天的笔记…',
    'notes.dayEmpty': '当天还没有笔记。',
    'notes.pickDay': '选择一天',
    'notes.legendEvent': '事件',
    'notes.legendNotes': '笔记',
    // unified calendar shell tabs
    'cal.earnings': '财报',
    'cal.macro': '宏观',
    'cal.ipo': 'IPO',
    // personal hub (/me) tabs
    'me.title': '我的',
    'me.overview': '今夜',
    'me.watchlist': '自选',
    'me.holdings': '持仓',
    'me.notes': '笔记',
    'me.alerts': '提醒',
    // overnight digest (Overview tab)
    'digest.aiTitle': '今夜综述',
    'digest.stocksTitle': '自选股隔夜',
    'digest.emptyTitle': '还没有自选股',
    'digest.emptySub': '添加自选股,每天早晨即可收到一份个性化的隔夜报告。',
    'digest.emptyCta': '添加自选股',
    'digest.error': '隔夜报告加载失败,请稍后再试。',
    // discussion shell tabs
    'disc.discussion': '讨论',
    'disc.community': '社区',
    'common.ago': '前',
    'common.showMore': '展开全文',
    'common.showLess': '收起',
    // indicator library
    'nav.indicators': '指标库',
    'ind.title': '美股指标大全',
    'ind.subtitle':
      '可检索的 {n} 项美股指标参考 —— 技术、基本面与情绪三大类,含公式、默认参数与解读要点。',
    'ind.search': '搜索指标 —— RSI、市盈率、MACD…',
    'ind.allDomains': '全部',
    'ind.domain.technical': '技术指标',
    'ind.domain.fundamental': '基本面',
    'ind.domain.sentiment': '情绪',
    'ind.allPriorities': '全部层级',
    'ind.priority.P0': '核心',
    'ind.priority.P1': '进阶',
    'ind.priority.P2': '专业',
    'ind.tierP0': '核心 (P0)',
    'ind.tierP1': '进阶 (P1)',
    'ind.tierP2': '专业 (P2)',
    'ind.matches': '{total} 项中匹配 {n} 项',
    'ind.formula': '公式',
    'ind.interpretation': '如何解读',
    'ind.params': '默认参数',
    'ind.output': '输出',
    'ind.inputs': '输入',
    'ind.lib': '库',
    'ind.empty': '没有符合筛选条件的指标',
    'ind.emptySub': '换个关键词,或清除筛选条件。',
    'ind.clear': '清除筛选',
    'ind.collapse': '收起',
    'ind.expand': '展开',
    'ind.footer': '仅为参考元数据 —— 公开、通用的指标定义。非投资建议。',
    'ind.coreNote': '高亮的为 MVP 核心指标 (P0)。',
    // 单指标详情页 (/indicators/{slug})。
    'ind3.crumbHome': '首页',
    'ind3.crumbLibrary': '指标库',
    'ind3.appliesTo': '适用:美股',
    'ind3.definition': '定义',
    'ind3.formula': '计算公式',
    'ind3.params': '默认参数',
    'ind3.interpretation': '解读要点',
    'ind3.dataSource': '数据来源',
    'ind3.disclaimer': '公开知识,不构成投资建议。',
    'ind3.related': '相关指标',
    'ind3.backToLibrary': '返回指标库',
    'ind3.seeOnStock': '在个股页查看该指标的实时计算',
    'ind3.metaInputs': '输入',
    'ind3.metaOutput': '输出',
    'ind3.metaLib': '库',
  },
};
